### ISSUE TITLE
Should fail act like mzero?

### ISSUE THREAD

**Issue by ocharles** [nikita-volkov/list-t#14]
There is no definition of `fail` for `ListT`, but I believe it should exist as:

```haskell
fail _ = mzero
```

This means pattern match failures don't crash, but short circuit.

**Comment by nikita-volkov** [comment]
Agreed! Resolved in 1.0.2

**Comment by ocharles** [comment]
Thank you!

**Comment by ocharles** [comment]
Unfortunately this fix still isn't correct. It works on GHC 8.6, where `fail = Control.Monad.Fail.fail`, but on 8.4, `Monad`'s `fail` is still calling `error`.

**Comment by nikita-volkov** [comment]
You're right. Fixed in 1.0.3
